### Get all semester 
# GET http://localhost:5000/
# Content-Type: application/json


### create user
POST http://localhost:5000/register
Content-Type: application/json

{
    "name":"Bappa6",
    "email":"bappa6@gmail.com",
    "password":"123456"
}


# ### update
# PATCH    http://localhost:5000/
# Content-Type: application/json

# {
    
# }