
### create user
POST http://localhost:9000/register
Content-Type: application/json

{
    "name":"bappa",
    "email":"bappa@gmail.com",
    "password":"12345"
}


### Get all semester 
GET http://localhost:9000
Content-Type: application/json

# ### update
# PATCH    http://localhost:5000/
# Content-Type: application/json

# {
    
# }